CREATE TABLE Courses (id INT AUTO_INCREMENT NOT NULL, teacher_id INT DEFAULT NULL, c_id INT NOT NULL, c_name VARCHAR(255) NOT NULL, c_description VARCHAR(255) NOT NULL, INDEX IDX_661863D041807E1D (teacher_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE course_enrollment (person_id INT NOT NULL, courses_id INT NOT NULL, INDEX IDX_43E9962217BBB47 (person_id), INDEX IDX_43E9962F9295384 (courses_id), PRIMARY KEY(person_id, courses_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE Courses ADD CONSTRAINT FK_661863D041807E1D FOREIGN KEY (teacher_id) REFERENCES Person (id);
ALTER TABLE course_enrollment ADD CONSTRAINT FK_43E9962217BBB47 FOREIGN KEY (person_id) REFERENCES Person (id) ON DELETE CASCADE;
ALTER TABLE course_enrollment ADD CONSTRAINT FK_43E9962F9295384 FOREIGN KEY (courses_id) REFERENCES Courses (id) ON DELETE CASCADE;
ALTER TABLE person CHANGE Sex Sex enum('male', 'female');
