<?php

namespace Edu\SisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
  public function findAll()
  {
    $q = $this->getEntityManager()
      ->createQuery("SELECT p FROM EduSisBundle:Person p");
    return $q->getResult();
  }
}
